-   id: dependency-version-fixer
    name: Dependency Version Fixer
    description: Fixes the version of the used Elements-based projects.
    language: python
    entry: dependency-version-fixer
    args: ['--with-cvmfs-branch', '--filter', '(Template/PPO_|PkgDef|PipScript|PipDef).*$']
    pass_filenames: false
    minimum_pre_commit_version: 0.15.0
